# Generated by Django 3.0.6 on 2020-09-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0007_auto_20200909_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cover_pic',
            field=models.FileField(upload_to='media/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='register_table',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='profiles/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=150),
        ),
    ]
