# Generated by Django 3.0.6 on 2020-09-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshop', '0009_auto_20200911_1215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact_us',
            options={'verbose_name_plural': 'Contact'},
        ),
        migrations.AlterField(
            model_name='add_product',
            name='product_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='add_product',
            name='sale_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='subject',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='register_table',
            name='gender',
            field=models.CharField(default='Male', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='register_table',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='profiles/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
